In [4]:
#1 -Import Data to your system:

#a) Create your own data frame
#b) Under "Data Services" > "Load Data" Load your data.  Then in the notebook under the "1010"/"Find and Add Data" menu item select your file and click "insert to code"
#c) Use existing data. For our purposes we will use R preloaded data.  For example mtcars

#View mtcars
head(mtcars)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [22]:
# 2 - Do something with the data
# Calculate average mpg per carburetor 

AvgMpg = aggregate(mtcars$mpg~mtcars$carb, FUN=mean)
AvgMpg

  mtcars$carb mtcars$mpg
1 1           25.34286
2 2           22.40000
3 3           16.30000
4 4           15.79000
5 6           19.70000
6 8           15.00000

In [23]:
#3 - Export the data to CSV

write.csv(AvgMpg,file='AvgMpg.csv')

In [26]:
#4 - Access the csv and put in objectstore

# Find your objectstore credentials: If you have data loaded to your project 
# under the menu item "1010"/"Find and Add Data" menu item.  
# Select any file and select "Insert Credentials"
# The below credentials are just examples with "xyz" under the actual parameters

credentials_2 <-list(auth_url = "https://identity.open.softlayer.com",project = "xyz",project_id = "xyz",region = "dallas",user_id = "xyz",domain_id = "xyz",domain_name = "xyz",username = "xyz",password = "xyz",container = "xyz",tenantId = "xyz",filename = ""xyz")

In [27]:
library('objectStoreR')
s = objectStore.put(credentials_2,'AvgMpg.csv')

In [20]:
#Then under the main menu: “Data Services” > “Object Storage”
# Click Project > Click File
#In “Select Action” menu pick “Download File”